version: "3"

volumes:
  client_node_modules:
  pwa_node_modules:
  _build:
  deps:
  gen:
  _build_glance:
  deps_glance:
  gen_glance:
services:
  pwa:
    image: node:14.8.0
    working_dir: "/opt/app"
    # network_mode doesn't work as expected on windows
    # network_mode: host
    ports:
      - 8080:8080
    volumes:
      - ./pwa:/opt/app
      - pwa_node_modules:/opt/app/node_modules
    command: bash -c "npm i && npm start"
    environment:
      SNOWPACK_PUBLIC_API_ORIGIN: http://localhost:8000
      SNOWPACK_PUBLIC_GLANCE_ORIGIN: http://localhost:9000
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    working_dir: /opt/app
    ports:
      - 8000:8000
    volumes:
      - ./service:/opt/app
      - _build:/opt/app/_build
      - deps:/opt/app/deps
      # NOTE Issue Gleam shouldn't delete gen directory.
      # - gen:/opt/app/gen
    # network_mode: host
    command: ./bin/start
    environment:
      PORT: 8000
      ORIGIN: http://localhost:8000
      CLIENT_ORIGIN: http://localhost:8080
      # DATABASE_URL: postgres://eEj8ar4O:OTnrE1n7D392DnbovK@localhost:6543/plum_mail
      DATABASE_URL: postgres://eEj8ar4O:OTnrE1n7D392DnbovK@db:5432/plum_mail
      DATABASE_SSL: "FALSE"
      POSTMARK_API_TOKEN: POSTMARK_DUMMY_TOKEN
      SECRET: DEV_SECRET
      SENTRY_DSN: https://e3b301fb356a4e61bebf8edb110af5b3@o351506.ingest.sentry.io/5574979
      ENVIRONMENT: local
    depends_on:
      - db
  db:
    image: "postgres:12.4"
    environment:
      - POSTGRES_USER=eEj8ar4O
      - POSTGRES_PASSWORD=OTnrE1n7D392DnbovK
      - POSTGRES_DB=plum_mail
    ports:
      - 6543:5432
