version: "3"

volumes:
  client_node_modules:
  _build:
  deps:
  gen:
  _build_glance:
  deps_glance:
  gen_glance:
services:
  client:
    image: node:14.8.0
    working_dir: "/opt/app"
    # network_mode doesn't work as expected on windows
    # network_mode: host
    ports:
      - 5000:5000
    volumes:
      - ./client:/opt/app
      - client_node_modules:/opt/app/node_modules
    command: bash -c "npm i && npm run start:dev"
    environment:
      API_ORIGIN: http://localhost:8000
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    working_dir: /opt/app
    volumes:
      - ./service:/opt/app
      - _build:/opt/app/_build
      - deps:/opt/app/deps
      # NOTE Issue Gleam shouldn't delete gen directory.
      # - gen:/opt/app/gen
    network_mode: host
    environment:
      PORT: 8000
      CLIENT_ORIGIN: http://localhost:5000
      DATABASE_URL: postgres://eEj8ar4O:OTnrE1n7D392DnbovK@localhost:6543/plum_mail
      DATABASE_SSL: "FALSE"
      POSTMARK_API_TOKEN: POSTMARK_DUMMY_TOKEN
    depends_on:
      - db
  db:
    image: "postgres:12.4"
    environment:
      - POSTGRES_USER=eEj8ar4O
      - POSTGRES_PASSWORD=OTnrE1n7D392DnbovK
      - POSTGRES_DB=plum_mail
    ports:
      - 6543:5432
