DROP TABLE memo_notifications;
DROP TABLE memos;
DROP TABLE pairs;
DROP TABLE link_tokens;
DROP TABLE participations;
DROP TABLE invitations;
DROP TABLE identifiers;
DROP TABLE groups;
DROP TABLE threads;
